#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="CVOr")]
public partial class CoachingDalDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertLastID(LastID instance);
  partial void UpdateLastID(LastID instance);
  partial void DeleteLastID(LastID instance);
  partial void InsertMail(Mail instance);
  partial void UpdateMail(Mail instance);
  partial void DeleteMail(Mail instance);
  #endregion
	
	public CoachingDalDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CVOrConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CoachingDalDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CoachingDalDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CoachingDalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CoachingDalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<LastID> LastIDs
	{
		get
		{
			return this.GetTable<LastID>();
		}
	}
	
	public System.Data.Linq.Table<Mail> Mails
	{
		get
		{
			return this.GetTable<Mail>();
		}
	}
}

[Table(Name="dbo.LastID")]
public partial class LastID : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _LastIDr;
	
	private long _LastIDID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLastIDrChanging(string value);
    partial void OnLastIDrChanged();
    partial void OnLastIDIDChanging(long value);
    partial void OnLastIDIDChanged();
    #endregion
	
	public LastID()
	{
		OnCreated();
	}
	
	[Column(Storage="_LastIDr", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string LastIDr
	{
		get
		{
			return this._LastIDr;
		}
		set
		{
			if ((this._LastIDr != value))
			{
				this.OnLastIDrChanging(value);
				this.SendPropertyChanging();
				this._LastIDr = value;
				this.SendPropertyChanged("LastIDr");
				this.OnLastIDrChanged();
			}
		}
	}
	
	[Column(Storage="_LastIDID", DbType="BigInt NOT NULL")]
	public long LastIDID
	{
		get
		{
			return this._LastIDID;
		}
		set
		{
			if ((this._LastIDID != value))
			{
				this.OnLastIDIDChanging(value);
				this.SendPropertyChanging();
				this._LastIDID = value;
				this.SendPropertyChanged("LastIDID");
				this.OnLastIDIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.Mail")]
public partial class Mail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MailID;
	
	private string _Mail1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMailIDChanging(string value);
    partial void OnMailIDChanged();
    partial void OnMail1Changing(string value);
    partial void OnMail1Changed();
    #endregion
	
	public Mail()
	{
		OnCreated();
	}
	
	[Column(Storage="_MailID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MailID
	{
		get
		{
			return this._MailID;
		}
		set
		{
			if ((this._MailID != value))
			{
				this.OnMailIDChanging(value);
				this.SendPropertyChanging();
				this._MailID = value;
				this.SendPropertyChanged("MailID");
				this.OnMailIDChanged();
			}
		}
	}
	
	[Column(Name="Mail", Storage="_Mail1", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Mail1
	{
		get
		{
			return this._Mail1;
		}
		set
		{
			if ((this._Mail1 != value))
			{
				this.OnMail1Changing(value);
				this.SendPropertyChanging();
				this._Mail1 = value;
				this.SendPropertyChanged("Mail1");
				this.OnMail1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
