<?xml version="1.0" encoding="utf-8"?>
<Database Name="CVYael" Class="CVYaelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HOME\MSSQLSERVER1;AttachDbFilename=|DataDirectory|\CvYael.mdf;Initial Catalog=CVYael;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CVYaelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LastID" Member="LastIDs">
    <Type Name="LastID">
      <Column Name="LastIDr" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastIDID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mail" Member="Mails">
    <Type Name="Mail">
      <Column Name="MailID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mail" Member="Mail1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>